### ISSUE TITLE
 Error on sending message TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by fstn** [botpress/botpress-hitl#9]
I get this error when I try to send a message to user using return bp.messenger.sendText(user.id, text, options);

`error: [FATAL] An unhandled exception occurred in your bot TypeError: Cannot read property 'id' of undefined
    at createUserSession (/node_modules/botpress-hitl/bin/webpack:/src/db.js:48:24)
    at /node_modules/botpress-hitl/bin/webpack:/src/db.js:75:14
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
18:13:08 - error: TypeError: Cannot read property 'id' of undefined
    at createUserSession (node_modules/botpress-hitl/bin/webpack:/src/db.js:48:24)
    at node_modules/botpress-hitl/bin/webpack:/src/db.js:75:14
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)`

**Comment by maherma-adg** [comment]
I have similar problem when trying to use botpress-hitl with botpress-platform-webchat.

Searching for root cause of this error, I found *bp.middlewares.sendOutgoing* try to read DB using *event.user.id*

Looking into hitl source, I see this value is not set in the outgoing event.

I solve the problem inserting this line in src/index.js:136
```
         user: {id: session.userId},
```

I don't know if problem is on hitl, webchat or botpress, but this workaround solve my problem.

Regards, 
Manuel

**Comment by maherma-adg** [comment]
I have similar problem when trying to use botpress-hitl with botpress-platform-webchat.

Look this [comment](https://github.com/botpress/botpress-hitl/issues/6#issuecomment-370269183)

could be useful for you
